language: node_js
node_js:
  - "8"
branches:
   only:
      - master
before_script:
   - npm install -g firebase-tools
   - npm install
script:
   - ng build --prod --aot
after_success:
   - firebase deploy --token $FIREBASE_TOKEN
notifications:
  email: false
